### PR TITLE
Add GitHub actions for CI

### PR DESCRIPTION
**Pull request by cosmo0920**
And also fixes chunk timekey glitch on CI.
This is because using time string contains `+03:00` but returned EventTime object does not contain `+03:00`.

CI result is:
https://github.com/cosmo0920/fluent-plugin-webhdfs/actions/runs/437614034

### CODE REVIEW

**Comment by repeatedly** [comment]
Can we see this result on PR?

**Comment by cosmo0920** [comment]
Here is the result: https://github.com/fluent/fluent-plugin-webhdfs/actions/runs/438759508

**Comment by repeatedly** [comment]
yeah, we can see it in actions page.
I want to know how to show the result like travis-ci integration. No way for now?

**Comment by cosmo0920** [comment]
For the next PR , we can see CI integration page like travis−ci.

**Comment by repeatedly** [comment]
Ah, I see. Awesome :)

**Pull request merged**
