### PR TITLE
add support bzip2 compression

### PR DESCRIPTION
**Pull request by wgzhao**
default gzip compression does not support splittable feature. add bzip2 compression alg.

### CODE REVIEW

**Comment by tagomoris** [comment]
This patch seems to miss to fix dependency for LZO and Bzip2.
Could you add these dependency and rebase on master/HEAD?

**Comment by okkez** [comment]
@tagomoris Can I rebase this PR after merge #32?

**Comment by tagomoris** [comment]
@okkez sure.

**Comment by okkez** [comment]
This branch does not work well.
I will re-implement these functionalities.

**Comment by tagomoris** [comment]
#35 will solve this issue.

**Pull request closed without merging**
