### PR TITLE
Introduce Compressor object

### PR DESCRIPTION
**Pull request by okkez**
This is stolen from fluent-plugin-s3.

### CODE REVIEW

**Comment by tagomoris** [comment]
Could you separate Compressor classes into another file for maintainancability?

**Comment by okkez** [comment]
I've extracted compressor classes.

**Comment by tagomoris** [comment]
Aren't `require` missing for compressor implementation classes?
And `< Fluent::TimeSlicedOutput` are missing for `class WebHDFSOutput`.

**Comment by okkez** [comment]
> Aren't require missing for compressor implementation classes?

[fluent-plugin-s3](https://github.com/fluent/fluent-plugin-s3/blob/master/lib/fluent/plugin/s3_compressor_lzma2.rb) works well.
I think fluentd can load compressor classes automatically.

> And < Fluent::TimeSlicedOutput are missing for class WebHDFSOutput.

We don't need `< Fluent::TimeSlicedOutput ` because WebHDFSOutput is already defined in compressor file.
I've testted this PR on VM.

**Comment by okkez** [comment]
Hmm, I need more test for this PR. :pray:

**Comment by tagomoris** [comment]
These compressor implementation classes will be loaded when Registry is initialized.
But it's not good practice to depend on the order of loading files. If anyone writes unit test for compressor implementation class and require it at first, then this code crashes.

**Comment by tagomoris** [comment]
It's true that it's missing to `require` files, because Registry does it.

**Comment by okkez** [comment]
I got it. Thank you for description.

**Comment by tagomoris** [comment]
Great to have! Please squash at last before merge.

**Comment by okkez** [comment]
Squashed!

**Comment by tagomoris** [comment]
Merged, and released as `v0.4.2`

**Comment by okkez** [comment]
Thanks!!

**Pull request merged**
