### PR TITLE
Add command compressors

### PR DESCRIPTION
**Pull request by okkez**
Add LZO and LZMA2.

### CODE REVIEW

**Comment by tagomoris** [comment]
Hadoop supports gzip, bzip2, lzo and snappy for transparent decoding on HDFS.
Are there any needs for lzma2?

**Comment by okkez** [comment]
> Are there any needs for lzma2?

No.
I've added compressors same as fluent-plugin-s3.

I will drop lzma2 support in this PR, so Hadoop does not support lzma2.
But snappy support needs another PR.

Thanks!

**Comment by okkez** [comment]
I've dropped lzma2 support and force pushed.

**Comment by tagomoris** [comment]
Merged. Thanks!

**Comment by tagomoris** [comment]
`v0.5.0` released.

**Pull request merged**
